//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPNETMVCCRUD.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Name cannot be blank")]
        [MaxLength(50, ErrorMessage = "Do not enter more than 50 characters")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Make sure you select a gender")]
        [MaxLength(6)]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Make sure you select a color")]
        [MaxLength(5)]
        public string Color { get; set; }
        [Required(ErrorMessage = "Make sure you enter a password")]
        [MaxLength(100)]
        public string Password { get; set; }
        [Display(Name = "Confirm Password")]
        public string ConfirmPassword { get; set; }
        public bool isAdmin { get; set; }
    }
}
